openapi: 3.0.0
info:
  title: OpenWeatherMap
  version: '1.0'
  description: |-
    Version: 2.5
    Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
  contact:
    email: 'some_email@gmail.com '
    url: 'https://openweathermap.org/api '
    name: OpenWeatherMap
  termsOfService: 'URL: https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'http://localhost:3000'
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: Your GET endpoint
      tags:
        - weather endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: Weather by Coordinate
                properties:
                  coord:
                    description: Weather by Coordinate
                    type: number
              examples:
                'example- coord:               type: object               properties:                 lon:                   type: number                 lat:                   type: number': {}
            application/xml:
              schema:
                type: object
                properties: {}
        '201':
          description: |
            401
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
            text/html:
              schema:
                type: object
                properties: {}
      operationId: get-weather
      description: 'Access current weather data for any location on Earth including over 200,000 cities! Current weather is frequently updated based on global models and data from more than 40,000 weather stations.'
      security:
        - API Key - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**Zip code**. Search by zip code. *Example: 95050,us*. Please note that if the country is not specified, the search uses USA as a default.'
components:
  schemas:
    '401':
      title: 401
      type: object
      properties:
        Message:
          type: string
        COD:
          type: integer
  securitySchemes:
    API Key - app_id:
      name: appid
      type: apiKey
      in: query
